package com.jesa.interviewslotmanager.entity;

public enum Permission
{
    CAN_CREATE_USER,
    CAN_UPDATE_USER,
    CAN_DELETE_USER,
    CAN_READ_USER,
    CAN_APPROVE_USER,

    CAN_CREATE_JOB,
    CAN_UPDATE_JOB,
    CAN_DELETE_JOB,
    CAN_READ_JOB,

    CAN_CREATE_SLOT,
    CAN_UPDATE_SLOT,
    CAN_DELETE_SLOT,
    CAN_READ_SLOT,

    CAN_CREATE_INTERVIEW,
    CAN_UPDATE_INTERVIEW,
    CAN_DELETE_INTERVIEW,
    CAN_READ_INTERVIEW,

    CAN_CREATE_DEPARTMENT,
    CAN_UPDATE_DEPARTMENT,
    CAN_DELETE_DEPARTMENT,
    CAN_READ_DEPARTMENT,

    CAN_CREATE_APPLICATION,
    CAN_UPDATE_APPLICATION,
    CAN_DELETE_APPLICATION,
    CAN_READ_APPLICATION,
}