-- created_by/last_modified_by hold the acting user's email, so every table sizes them to
-- match users.email. A narrower column fails audited writes at commit for long addresses.
CREATE TABLE users
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                UUID         NOT NULL CONSTRAINT uk_users_public_id UNIQUE,
    email                    VARCHAR(255) NOT NULL CONSTRAINT uk_users_email UNIQUE,
    password                 VARCHAR(255) NOT NULL,
    first_name               VARCHAR(255) NOT NULL,
    last_name                VARCHAR(255) NOT NULL,
    phone_number             VARCHAR(255),
    is_approved              BOOLEAN      NOT NULL,
    email_verified           BOOLEAN      NOT NULL DEFAULT FALSE,
    must_change_password     BOOLEAN      NOT NULL DEFAULT FALSE,
    resume_object_key        VARCHAR(512),
    resume_original_filename VARCHAR(255),
    resume_content_type      VARCHAR(100),
    resume_size_bytes        BIGINT,
    resume_uploaded_at       TIMESTAMP(6) WITH TIME ZONE,
    created_by               VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date             TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by         VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_pending_approval ON users (id)
    WHERE is_approved = FALSE;

CREATE TABLE user_roles
(
    user_id BIGINT       NOT NULL CONSTRAINT fk_user_roles_user REFERENCES users (id),
    roles   VARCHAR(255) NOT NULL,
    -- Composite PK: a user can hold each role at most once.
    PRIMARY KEY (user_id, roles)
);

CREATE INDEX idx_user_roles_roles ON user_roles (roles);

CREATE TABLE refresh_tokens
(
    id          UUID         NOT NULL PRIMARY KEY,
    token_hash  BYTEA        NOT NULL CONSTRAINT uk_refresh_tokens_token_hash UNIQUE CONSTRAINT ck_refresh_tokens_token_hash_length CHECK (octet_length(token_hash) = 32),
    user_id     BIGINT       NOT NULL CONSTRAINT fk_refresh_tokens_user REFERENCES users (id) ON DELETE CASCADE,
    expires_at  TIMESTAMP(6) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    consumed    BOOLEAN      NOT NULL,
    revoked     BOOLEAN      NOT NULL,
    device_info VARCHAR(255),
    ip_address  VARCHAR(255)
);

CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX idx_refresh_tokens_revoked ON refresh_tokens (id)
    WHERE revoked = TRUE;
CREATE INDEX idx_refresh_tokens_active_expires_at ON refresh_tokens (expires_at)
    WHERE consumed = FALSE AND revoked = FALSE;
CREATE INDEX idx_refresh_tokens_active_user_created_at ON refresh_tokens (user_id, created_at DESC)
    WHERE consumed = FALSE AND revoked = FALSE;

CREATE TABLE email_verification_tokens
(
    id         UUID         NOT NULL PRIMARY KEY,
    token_hash BYTEA        NOT NULL CONSTRAINT uk_email_verification_tokens_token_hash UNIQUE CONSTRAINT ck_email_verification_tokens_token_hash_length CHECK (octet_length(token_hash) = 32),
    user_id    BIGINT       NOT NULL CONSTRAINT fk_email_verification_tokens_user REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    used       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_email_verification_tokens_expires_at ON email_verification_tokens (expires_at);
-- Only unused tokens are ever looked up
CREATE INDEX idx_email_verification_tokens_active_user ON email_verification_tokens (user_id)
    WHERE used = FALSE;

CREATE TABLE password_reset_tokens
(
    id         UUID         NOT NULL PRIMARY KEY,
    token_hash BYTEA        NOT NULL CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE CONSTRAINT ck_password_reset_tokens_token_hash_length CHECK (octet_length(token_hash) = 32),
    user_id    BIGINT       NOT NULL CONSTRAINT fk_password_reset_tokens_user REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    used       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens (expires_at);
CREATE INDEX idx_password_reset_tokens_active_user ON password_reset_tokens (user_id)
    WHERE used = FALSE;

CREATE TABLE departments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID         NOT NULL CONSTRAINT uk_departments_public_id UNIQUE,
    name               VARCHAR(255) NOT NULL CONSTRAINT uk_departments_name UNIQUE,
    description        VARCHAR(255),
    created_by         VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version            BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE skills
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100) NOT NULL,
    slug               VARCHAR(120) NOT NULL CONSTRAINT uk_skills_slug UNIQUE,
    created_by         VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job_postings
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                UUID         NOT NULL CONSTRAINT uk_job_postings_public_id UNIQUE,
    reference_code           VARCHAR(50)  NOT NULL CONSTRAINT uk_job_postings_reference_code UNIQUE,
    slug                     VARCHAR(180) NOT NULL CONSTRAINT uk_job_postings_slug UNIQUE,
    department_id            BIGINT       NOT NULL CONSTRAINT fk_job_postings_department REFERENCES departments (id),
    title                    VARCHAR(180) NOT NULL,
    description              TEXT,
    application_deadline     TIMESTAMP(6),
    planned_start_date       DATE,
    salary_min               INTEGER,
    salary_max               INTEGER,
    salary_currency          VARCHAR(3),
    salary_period            VARCHAR(30),
    salary_negotiable        BOOLEAN      NOT NULL DEFAULT FALSE,
    city                     VARCHAR(50),
    remote_policy            VARCHAR(30)  NOT NULL,
    experience_level         VARCHAR(30),
    minimum_experience_years INTEGER,
    open_positions           INTEGER      NOT NULL DEFAULT 1,
    employment_type          VARCHAR(30)  NOT NULL,
    contract_type            VARCHAR(30)  NOT NULL,
    status                   VARCHAR(30)  NOT NULL,
    scheduled_publish_at     TIMESTAMP(6),
    published_at             TIMESTAMP(6),
    closed_at                TIMESTAMP(6),
    created_by               VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date             TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by         VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version                  BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX idx_job_postings_department_status ON job_postings (department_id, status);
CREATE INDEX idx_job_postings_status_published ON job_postings (status, published_at);
CREATE INDEX idx_job_postings_application_deadline ON job_postings (application_deadline);

CREATE TABLE job_skills
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id     BIGINT      NOT NULL CONSTRAINT fk_job_skills_job REFERENCES job_postings (id),
    skill_id   BIGINT      NOT NULL CONSTRAINT fk_job_skills_skill REFERENCES skills (id),
    importance VARCHAR(20) NOT NULL,
    CONSTRAINT uk_job_skills_job_skill UNIQUE (job_id, skill_id)
);

CREATE INDEX idx_job_skills_skill_importance ON job_skills (skill_id, importance);
CREATE INDEX idx_job_skills_required_skill ON job_skills (skill_id, job_id)
    WHERE importance = 'REQUIRED';

-- Keeping an interviewer's slots from overlapping means indexing a scalar (the interviewer)
-- next to a range in the same GiST index; btree_gist supplies the scalar operator classes.
-- It is a trusted extension since PostgreSQL 13, so the database owner installs it without
-- superuser rights.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE slots
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID                        NOT NULL CONSTRAINT uk_slots_public_id UNIQUE,
    interviewer_id     BIGINT                      NOT NULL CONSTRAINT fk_slots_interviewer REFERENCES users (id),
    is_available       BOOLEAN                     NOT NULL,
    -- Absolute points on the timeline, stored in UTC. A slot is an agreement between two
    -- people who may sit in different zones, so the wall-clock reading is left to the
    -- client and nothing here depends on the server's zone.
    start_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    end_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by         VARCHAR(255)                NOT NULL DEFAULT 'system',
    created_date       TIMESTAMP(6)                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255)                NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6)                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version            BIGINT                      NOT NULL DEFAULT 0,

    CONSTRAINT ck_slots_time_range CHECK (end_at > start_at),
    -- Nobody can be in two interviews at once: no two slots of the same interviewer may share a moment.
    -- The range is half-open so back-to-back slots touch without overlapping,
    -- and the constraint holds under concurrency where a SELECT-then-INSERT check cannot.
    CONSTRAINT ex_slots_interviewer_no_overlap EXCLUDE USING gist (
        interviewer_id WITH =, tstzrange(start_at, end_at, '[)') WITH &&)
);

CREATE INDEX idx_slots_interviewer ON slots (interviewer_id);
CREATE INDEX idx_slots_available_start_at ON slots (start_at)
    WHERE is_available = TRUE;

CREATE TABLE applications
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                UUID         NOT NULL CONSTRAINT uk_applications_public_id UNIQUE,
    job_id                   BIGINT       NOT NULL CONSTRAINT fk_applications_job REFERENCES job_postings (id),
    user_id                  BIGINT       NOT NULL CONSTRAINT fk_applications_candidate REFERENCES users (id),
    status                   VARCHAR(255) NOT NULL,
    resume_object_key        VARCHAR(512),
    resume_original_filename VARCHAR(255),
    resume_content_type      VARCHAR(100),
    resume_size_bytes        BIGINT,
    resume_uploaded_at       TIMESTAMP(6) WITH TIME ZONE,
    applied_at               TIMESTAMP(6),
    created_by               VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date             TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by         VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version                  BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_applications_job_candidate UNIQUE (job_id, user_id)
);

CREATE INDEX idx_applications_candidate ON applications (user_id);
CREATE INDEX idx_applications_active_status ON applications (status, id)
    WHERE status IN ('PENDING', 'UNDER_REVIEW', 'INTERVIEW_SCHEDULED');

CREATE TABLE interviews
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID         NOT NULL CONSTRAINT uk_interviews_public_id UNIQUE,
    application_id     BIGINT       NOT NULL CONSTRAINT fk_interviews_application REFERENCES applications (id),
    interviewer_id     BIGINT       NOT NULL CONSTRAINT fk_interviews_interviewer REFERENCES users (id),
    slot_id            BIGINT CONSTRAINT uk_interviews_slot UNIQUE CONSTRAINT fk_interviews_slot REFERENCES slots (id),
    status             VARCHAR(255) NOT NULL,
    notes              TEXT,
    recommendation     VARCHAR(20),
    is_online          BOOLEAN      NOT NULL DEFAULT FALSE,
    meeting_url        VARCHAR(512),
    created_by         VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by   VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version            BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX idx_interviews_application ON interviews (application_id);
CREATE INDEX idx_interviews_interviewer ON interviews (interviewer_id);
