CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    is_approved BOOLEAN NOT NULL,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    resume_object_key VARCHAR(512),
    resume_original_filename VARCHAR(255),
    resume_content_type VARCHAR(100),
    resume_size_bytes BIGINT,
    resume_uploaded_at TIMESTAMP(6),
    created_by VARCHAR(50) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_public_id UNIQUE (public_id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE INDEX idx_users_pending_approval ON users (id)
    WHERE is_approved = FALSE;

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    roles VARCHAR(255),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_user_roles_roles ON user_roles (roles);

CREATE TABLE refresh_tokens (
    id UUID NOT NULL,
    token_hash BYTEA NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    consumed BOOLEAN NOT NULL,
    revoked BOOLEAN NOT NULL,
    device_info VARCHAR(255),
    ip_address VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_refresh_tokens_token_hash_length CHECK (octet_length(token_hash) = 32),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX idx_refresh_tokens_revoked ON refresh_tokens (id)
    WHERE revoked = TRUE;
CREATE INDEX idx_refresh_tokens_active_expires_at ON refresh_tokens (expires_at)
    WHERE consumed = FALSE AND revoked = FALSE;
CREATE INDEX idx_refresh_tokens_active_user_created_at ON refresh_tokens (user_id, created_at DESC)
    WHERE consumed = FALSE AND revoked = FALSE;

CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_by VARCHAR(50) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_departments_public_id UNIQUE (public_id),
    CONSTRAINT uk_departments_name UNIQUE (name)
);

CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    created_by VARCHAR(50) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_skills_slug UNIQUE (slug)
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    department_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    applying_deadline DATE,
    salary_min INTEGER,
    salary_max INTEGER,
    salary_currency VARCHAR(3),
    salary_period VARCHAR(255),
    salary_visible BOOLEAN NOT NULL DEFAULT TRUE,
    location VARCHAR(255),
    remote_policy VARCHAR(255),
    experience_level VARCHAR(255),
    open_positions INTEGER NOT NULL DEFAULT 1,
    employment_type VARCHAR(255) NOT NULL,
    contract_type VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    created_by VARCHAR(50) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    search_vector TSVECTOR GENERATED ALWAYS AS (
        setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(description, '')), 'B')
    ) STORED,
    PRIMARY KEY (id),
    CONSTRAINT uk_jobs_public_id UNIQUE (public_id),
    CONSTRAINT fk_jobs_department
        FOREIGN KEY (department_id) REFERENCES departments (id)
);

CREATE INDEX idx_jobs_open_deadline ON jobs (applying_deadline)
    WHERE status = 'OPEN';
CREATE INDEX idx_jobs_open_department_deadline ON jobs (department_id, applying_deadline)
    WHERE status = 'OPEN';
CREATE INDEX idx_jobs_search_vector ON jobs USING GIN (search_vector);

CREATE TABLE job_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    importance VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_job_skills_job_skill UNIQUE (job_id, skill_id),
    CONSTRAINT fk_job_skills_job
        FOREIGN KEY (job_id) REFERENCES jobs (id),
    CONSTRAINT fk_job_skills_skill
        FOREIGN KEY (skill_id) REFERENCES skills (id)
);

CREATE INDEX idx_job_skills_skill_importance ON job_skills (skill_id, importance);
CREATE INDEX idx_job_skills_required_skill ON job_skills (skill_id, job_id)
    WHERE importance = 'REQUIRED';

CREATE TABLE slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    interviewer_id BIGINT NOT NULL,
    is_available BOOLEAN NOT NULL,
    interview_date DATE,
    start_time TIME(6),
    end_time TIME(6),
    created_by VARCHAR(50) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_slots_public_id UNIQUE (public_id),
    CONSTRAINT fk_slots_interviewer
        FOREIGN KEY (interviewer_id) REFERENCES users (id)
);

CREATE INDEX idx_slots_interviewer ON slots (interviewer_id);
CREATE INDEX idx_slots_available_date ON slots (interview_date, start_time)
    WHERE is_available = TRUE;

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    job_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    resume_object_key VARCHAR(512),
    resume_original_filename VARCHAR(255),
    resume_content_type VARCHAR(100),
    resume_size_bytes BIGINT,
    resume_uploaded_at TIMESTAMP(6),
    applied_at TIMESTAMP(6),
    created_by VARCHAR(50) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_applications_public_id UNIQUE (public_id),
    CONSTRAINT uk_applications_job_candidate UNIQUE (job_id, user_id),
    CONSTRAINT fk_applications_job
        FOREIGN KEY (job_id) REFERENCES jobs (id),
    CONSTRAINT fk_applications_candidate
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_applications_candidate ON applications (user_id);
CREATE INDEX idx_applications_active_status ON applications (status, id)
    WHERE status IN ('PENDING', 'UNDER_REVIEW', 'INTERVIEW_SCHEDULED');

CREATE TABLE interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    application_id BIGINT NOT NULL,
    interviewer_id BIGINT NOT NULL,
    slot_id BIGINT,
    status VARCHAR(255) NOT NULL,
    notes TEXT,
    is_online BOOLEAN NOT NULL DEFAULT FALSE,
    meeting_url VARCHAR(512),
    created_by VARCHAR(50) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_interviews_public_id UNIQUE (public_id),
    CONSTRAINT uk_interviews_slot UNIQUE (slot_id),
    CONSTRAINT fk_interviews_application
        FOREIGN KEY (application_id) REFERENCES applications (id),
    CONSTRAINT fk_interviews_interviewer
        FOREIGN KEY (interviewer_id) REFERENCES users (id),
    CONSTRAINT fk_interviews_slot
        FOREIGN KEY (slot_id) REFERENCES slots (id)
);

CREATE INDEX idx_interviews_application ON interviews (application_id);
CREATE INDEX idx_interviews_interviewer ON interviews (interviewer_id);
