-- created_by/last_modified_by hold the acting user's email, so every table sizes them to
-- match users.email. A narrower column fails audited writes at commit for long addresses.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    is_approved BOOLEAN NOT NULL,
    -- Set once the user proves ownership of their email address (or implicitly for
    -- staff/admin accounts whose initial password is delivered by email).
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    resume_object_key VARCHAR(512),
    resume_original_filename VARCHAR(255),
    resume_content_type VARCHAR(100),
    resume_size_bytes BIGINT,
    resume_uploaded_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_public_id UNIQUE (public_id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE INDEX idx_users_pending_approval ON users (id)
    WHERE is_approved = FALSE;

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    roles VARCHAR(255) NOT NULL,
    -- Composite PK: a user can hold each role at most once.
    PRIMARY KEY (user_id, roles),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_user_roles_roles ON user_roles (roles);

CREATE TABLE refresh_tokens (
    id UUID NOT NULL,
    token_hash BYTEA NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    consumed BOOLEAN NOT NULL,
    revoked BOOLEAN NOT NULL,
    device_info VARCHAR(255),
    ip_address VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_refresh_tokens_token_hash_length CHECK (octet_length(token_hash) = 32),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX idx_refresh_tokens_revoked ON refresh_tokens (id)
    WHERE revoked = TRUE;
CREATE INDEX idx_refresh_tokens_active_expires_at ON refresh_tokens (expires_at)
    WHERE consumed = FALSE AND revoked = FALSE;
CREATE INDEX idx_refresh_tokens_active_user_created_at ON refresh_tokens (user_id, created_at DESC)
    WHERE consumed = FALSE AND revoked = FALSE;

-- Single-use tokens proving ownership of a registration email address. Only the
-- HMAC-SHA256 hash of the raw token is stored (same scheme as password_reset_tokens).
CREATE TABLE email_verification_tokens (
    id UUID NOT NULL,
    token_hash BYTEA NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    CONSTRAINT uk_email_verification_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_email_verification_tokens_token_hash_length CHECK (octet_length(token_hash) = 32),
    CONSTRAINT fk_email_verification_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_email_verification_tokens_expires_at ON email_verification_tokens (expires_at);
-- Only unused tokens are ever looked up; keep that lookup lean.
CREATE INDEX idx_email_verification_tokens_active_user ON email_verification_tokens (user_id)
    WHERE used = FALSE;

CREATE TABLE password_reset_tokens (
    id UUID NOT NULL,
    token_hash BYTEA NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_password_reset_tokens_token_hash_length CHECK (octet_length(token_hash) = 32),
    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens (expires_at);
-- Only unused tokens are ever looked up; keep that lookup lean.
CREATE INDEX idx_password_reset_tokens_active_user ON password_reset_tokens (user_id)
    WHERE used = FALSE;

CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_departments_public_id UNIQUE (public_id),
    CONSTRAINT uk_departments_name UNIQUE (name)
);

CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_skills_slug UNIQUE (slug)
);

CREATE TABLE job_postings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    reference_code VARCHAR(50) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    department_id BIGINT NOT NULL,
    title VARCHAR(180) NOT NULL,
    description TEXT,
    application_deadline TIMESTAMP(6),
    planned_start_date DATE,
    salary_min INTEGER,
    salary_max INTEGER,
    salary_currency VARCHAR(3),
    salary_period VARCHAR(30),
    salary_negotiable BOOLEAN NOT NULL DEFAULT FALSE,
    city VARCHAR(50),
    remote_policy VARCHAR(30) NOT NULL,
    experience_level VARCHAR(30),
    minimum_experience_years INTEGER,
    open_positions INTEGER NOT NULL DEFAULT 1,
    employment_type VARCHAR(30) NOT NULL,
    contract_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    scheduled_publish_at TIMESTAMP(6),
    published_at TIMESTAMP(6),
    closed_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_job_postings_public_id UNIQUE (public_id),
    CONSTRAINT uk_job_postings_reference_code UNIQUE (reference_code),
    CONSTRAINT uk_job_postings_slug UNIQUE (slug),
    CONSTRAINT fk_job_postings_department
        FOREIGN KEY (department_id) REFERENCES departments (id)
);

CREATE INDEX idx_job_postings_department_status ON job_postings (department_id, status);
CREATE INDEX idx_job_postings_status_published ON job_postings (status, published_at);
CREATE INDEX idx_job_postings_application_deadline ON job_postings (application_deadline);

CREATE TABLE job_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    importance VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_job_skills_job_skill UNIQUE (job_id, skill_id),
    CONSTRAINT fk_job_skills_job
        FOREIGN KEY (job_id) REFERENCES job_postings (id),
    CONSTRAINT fk_job_skills_skill
        FOREIGN KEY (skill_id) REFERENCES skills (id)
);

CREATE INDEX idx_job_skills_skill_importance ON job_skills (skill_id, importance);
CREATE INDEX idx_job_skills_required_skill ON job_skills (skill_id, job_id)
    WHERE importance = 'REQUIRED';

CREATE TABLE slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    interviewer_id BIGINT NOT NULL,
    is_available BOOLEAN NOT NULL,
    interview_date DATE,
    start_time TIME(6),
    end_time TIME(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_slots_public_id UNIQUE (public_id),
    -- A slot's window must move forward in time (NULL when unset, which passes).
    CONSTRAINT ck_slots_time_range CHECK (end_time > start_time),
    -- Date, start and end describe one window: all set together, or all absent.
    CONSTRAINT ck_slots_window_all_or_none CHECK (
        (interview_date IS NULL) = (start_time IS NULL)
        AND (start_time IS NULL) = (end_time IS NULL)
    ),
    CONSTRAINT fk_slots_interviewer
        FOREIGN KEY (interviewer_id) REFERENCES users (id)
);

CREATE INDEX idx_slots_interviewer ON slots (interviewer_id);
CREATE INDEX idx_slots_available_date ON slots (interview_date, start_time)
    WHERE is_available = TRUE;

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    job_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    resume_object_key VARCHAR(512),
    resume_original_filename VARCHAR(255),
    resume_content_type VARCHAR(100),
    resume_size_bytes BIGINT,
    resume_uploaded_at TIMESTAMP(6) WITH TIME ZONE,
    applied_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_applications_public_id UNIQUE (public_id),
    CONSTRAINT uk_applications_job_candidate UNIQUE (job_id, user_id),
    CONSTRAINT fk_applications_job
        FOREIGN KEY (job_id) REFERENCES job_postings (id),
    CONSTRAINT fk_applications_candidate
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_applications_candidate ON applications (user_id);
CREATE INDEX idx_applications_active_status ON applications (status, id)
    WHERE status IN ('PENDING', 'UNDER_REVIEW', 'INTERVIEW_SCHEDULED');

CREATE TABLE interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    application_id BIGINT NOT NULL,
    interviewer_id BIGINT NOT NULL,
    slot_id BIGINT,
    status VARCHAR(255) NOT NULL,
    notes TEXT,
    recommendation VARCHAR(20),
    is_online BOOLEAN NOT NULL DEFAULT FALSE,
    meeting_url VARCHAR(512),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    created_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_date TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_interviews_public_id UNIQUE (public_id),
    CONSTRAINT uk_interviews_slot UNIQUE (slot_id),
    CONSTRAINT fk_interviews_application
        FOREIGN KEY (application_id) REFERENCES applications (id),
    CONSTRAINT fk_interviews_interviewer
        FOREIGN KEY (interviewer_id) REFERENCES users (id),
    CONSTRAINT fk_interviews_slot
        FOREIGN KEY (slot_id) REFERENCES slots (id)
);

CREATE INDEX idx_interviews_application ON interviews (application_id);
CREATE INDEX idx_interviews_interviewer ON interviews (interviewer_id);
