spring.application.name=interview-slot-manager

spring.datasource.url=jdbc:mysql://localhost:3306/KRINO
spring.datasource.username=root
spring.datasource.password=A988EE988
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


jwt.secret=V29uZGVyZnVsU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb25Jc05lZWRlZEhlcmU=
#jwt.expiration.ms=360000

app.jwt.access-token-expiration.ms=900000
app.jwt.refresh-token-expiration.ms=604800000
app.jwt.issuer=interview-slot-manager
app.CookieName=KHB-Cookie
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

app.admin.email=khbabez7@gmail.com
app.admin.password=admin123

app.cors.allowed-origins=http://localhost:5173