package com.krino.backend.utility;

public enum ErrorCode
{
    METHOD_NOT_SUPPORTED,
    MALFORMED_JSON,

    UNEXPECTED_ERROR,
    INVALID_REQUEST_BODY,
    RESOURCE_NOT_FOUND,
    INVALID_REFRESH_TOKEN,
    INVALID_TOKEN,
    TOKEN_ERROR,
    ACCESS_DENIED,

    EMAIL_ALREADY_IN_USE,
    EMAIL_ALREADY_EXISTS,
    PASSWORD_TOO_WEAK,
    INVALID_EMAIL_FORMAT,

    INVALID_CREDENTIALS,
    ACCOUNT_DISABLED,
    ACCOUNT_LOCKED,
    ACCOUNT_NOT_VERIFIED,

    PASSWORD_CHANGE_FAILED,
    PASSWORD_RESET_TOKEN_EXPIRED,
    INVALID_PASSWORD_RESET_TOKEN,
    NEW_PASSWORD_SAME_AS_OLD,
    AUTHENTICATION_REQUIRED,
    AUTHENTICATION_FAILED,
    INCORRECT_PASSWORD,

    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    VALIDATION_FAILED,
    RESOURCE_CONFLICT, INTERNAL_SERVER_ERROR,

    DEPARTMENT_NOT_FOUND,
    DEPARTMENT_ALREADY_EXISTS,
    DEPARTMENT_ID_NOT_FOUND,
    DEPARTMENT_NAME_NOT_FOUND,
    DEPARTMENT_DESCRIPTION_NOT_FOUND,

    JOB_NOT_FOUND,
    JOB_ALREADY_EXISTS,
    JOB_ID_NOT_FOUND,
    JOB_NAME_NOT_FOUND,
    JOB_DESCRIPTION_NOT_FOUND,
    JOB_STATUS_NOT_FOUND,
    INVALID_JOB_TYPE,
}