package com.jesa.interviewslotmanager.utility;

public enum ErrorCode
{

    UNEXPECTED_ERROR,
    INVALID_REQUEST_BODY,
    RESOURCE_NOT_FOUND,
    INVALID_TOKEN,
    TOKEN_ERROR,
    ACCESS_DENIED,

    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_IN_USE,
    EMAIL_ALREADY_EXISTS,
    PASSWORD_TOO_WEAK,
    INVALID_EMAIL_FORMAT,
    INVALID_USERNAME_FORMAT,

    INVALID_CREDENTIALS,
    ACCOUNT_DISABLED,
    ACCOUNT_LOCKED,
    ACCOUNT_NOT_VERIFIED,

    PASSWORD_CHANGE_FAILED,
    PASSWORD_RESET_TOKEN_EXPIRED,
    INVALID_PASSWORD_RESET_TOKEN,
    NEW_PASSWORD_SAME_AS_OLD,
    AUTHENTICATION_REQUIRED,
    AUTHENTICATION_FAILED,
    INCORRECT_PASSWORD,

    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    VALIDATION_FAILED,
    INTERNAL_SERVER_ERROR
}